import { MigrationInterface, QueryRunner } from 'typeorm';

const BASELINE_STATEMENTS = [
  `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`,
  `CREATE TABLE "workflows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "yaml_definition" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5b5757cc1cd86268019fef52e0c" PRIMARY KEY ("id"));`,
  `CREATE TYPE "public"."workflow_runs_status_enum" AS ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED');`,
  `CREATE TABLE "workflow_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflow_id" character varying NOT NULL, "status" "public"."workflow_runs_status_enum" NOT NULL DEFAULT 'PENDING', "current_step_id" character varying, "state_variables" jsonb NOT NULL DEFAULT '{}', "concurrency_scope" character varying(512), "launch_dedupe_key" character varying(512), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eea9f8d0a660b3f48114c313233" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_a2995918456c0a612cf1e5ba22" ON "workflow_runs" ("workflow_id") ;`,
  `CREATE INDEX "IDX_15ee5ec3047cb2dca0101f96f9" ON "workflow_runs" ("concurrency_scope") ;`,
  `CREATE INDEX "IDX_4503f970017c16da72000bd2d4" ON "workflow_runs" ("launch_dedupe_key") ;`,
  `CREATE TYPE "public"."scheduled_jobs_schedule_scope_enum" AS ENUM('scope', 'global');`,
  `CREATE TYPE "public"."scheduled_jobs_status_enum" AS ENUM('active', 'paused');`,
  `CREATE TYPE "public"."scheduled_jobs_schedule_type_enum" AS ENUM('one_time', 'interval', 'cron');`,
  `CREATE TYPE "public"."scheduled_jobs_execution_target_type_enum" AS ENUM('workflow');`,
  `CREATE TABLE "scheduled_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schedule_scope" "public"."scheduled_jobs_schedule_scope_enum" NOT NULL DEFAULT 'scope', "scope_id" uuid, "name" character varying(180) NOT NULL, "status" "public"."scheduled_jobs_status_enum" NOT NULL DEFAULT 'active', "schedule_type" "public"."scheduled_jobs_schedule_type_enum" NOT NULL, "schedule_expression" text NOT NULL, "timezone" character varying(128), "next_run_at" TIMESTAMP WITH TIME ZONE, "execution_target_type" "public"."scheduled_jobs_execution_target_type_enum" NOT NULL DEFAULT 'workflow', "execution_target_ref" uuid NOT NULL, "payload_json" jsonb NOT NULL DEFAULT '{}', "created_by" character varying(255), "updated_by" character varying(255), "paused_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_119312a5470a95ee9c733a5246d" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_scheduled_jobs_status_next_run" ON "scheduled_jobs" ("status", "next_run_at") ;`,
  `CREATE INDEX "idx_scheduled_jobs_scope_status_next_run" ON "scheduled_jobs" ("scope_id", "status", "next_run_at") ;`,
  `CREATE INDEX "idx_scheduled_jobs_schedule_scope_status_next_run" ON "scheduled_jobs" ("schedule_scope", "status", "next_run_at") ;`,
  `CREATE TYPE "public"."scheduled_job_runs_status_enum" AS ENUM('triggered', 'running', 'succeeded', 'failed', 'skipped', 'cancelled');`,
  `CREATE TABLE "scheduled_job_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scheduled_job_id" uuid NOT NULL, "status" "public"."scheduled_job_runs_status_enum" NOT NULL DEFAULT 'triggered', "due_at" TIMESTAMP WITH TIME ZONE NOT NULL, "triggered_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "started_at" TIMESTAMP WITH TIME ZONE, "finished_at" TIMESTAMP WITH TIME ZONE, "workflow_run_id" uuid, "error_code" character varying(120), "error_message" text, "diagnostics_json" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_259c46aa735509a3c94ecfd962f" PRIMARY KEY ("id"));`,
  `CREATE UNIQUE INDEX "uq_scheduled_job_runs_due_key" ON "scheduled_job_runs" ("scheduled_job_id", "due_at") ;`,
  `CREATE INDEX "idx_scheduled_job_runs_workflow_run" ON "scheduled_job_runs" ("workflow_run_id") ;`,
  `CREATE INDEX "idx_scheduled_job_runs_job_triggered" ON "scheduled_job_runs" ("scheduled_job_id", "triggered_at") ;`,
  `CREATE TABLE "workflow_launch_presets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflow_id" character varying(255) NOT NULL, "scope_id" character varying(255), "name" character varying(120) NOT NULL, "trigger_data" jsonb NOT NULL DEFAULT '{}', "created_by" character varying(255), "updated_by" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ec801581174ed4056ce1020bbd7" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_workflow_launch_presets_workflow_name" ON "workflow_launch_presets" ("workflow_id", "name") ;`,
  `CREATE INDEX "idx_workflow_launch_presets_workflow_scope" ON "workflow_launch_presets" ("workflow_id", "scope_id") ;`,
  `CREATE TABLE "tool_registry" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "schema" jsonb NOT NULL, "typescript_code" text NOT NULL, "tier_restriction" integer NOT NULL DEFAULT '0', "runtime_owner" character varying(16), "transport" character varying(32), "api_callback" jsonb, "language" character varying(16), "publication_status" character varying(32), "mcp_server_id" uuid, "published_artifact_id" uuid, "published_version" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_181f749db5aec69a028ccfa8d37" UNIQUE ("name"), CONSTRAINT "PK_b5c6729c70067bfb4eec31c261d" PRIMARY KEY ("id"));`,
  `CREATE TABLE "pi_session_trees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflow_run_id" uuid, "chat_session_id" uuid, "container_tier" integer NOT NULL, "jsonl_data" jsonb NOT NULL DEFAULT '[]', "last_leaf_node_id" character varying, "archived_at" TIMESTAMP WITH TIME ZONE, "archive_reason" character varying(128), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2056836938e4d24ca311f3458a4" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_a8b0b2b7a1711112a0f4e2af3f" ON "pi_session_trees" ("workflow_run_id") ;`,
  `CREATE INDEX "IDX_17a73093e83e7445c7f3a88b23" ON "pi_session_trees" ("chat_session_id") ;`,
  `CREATE INDEX "IDX_5403ff5bac34ca8ab9652a90a7" ON "pi_session_trees" ("archived_at") ;`,
  `CREATE TYPE "public"."memory_segments_memory_type_enum" AS ENUM('preference', 'fact', 'history');`,
  `CREATE TABLE "memory_segments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entity_type" character varying NOT NULL, "entity_id" character varying NOT NULL, "memory_type" "public"."memory_segments_memory_type_enum" NOT NULL DEFAULT 'fact', "content" text NOT NULL, "version" integer NOT NULL DEFAULT '1', "metadata_json" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d57207ff2858ddd5c70a55272cf" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_8464026d4287c67ab90911b3ed" ON "memory_segments" ("entity_type", "entity_id") ;`,
  `CREATE TYPE "public"."subagent_executions_status_enum" AS ENUM('Spawning', 'Running', 'Completed', 'Failed');`,
  `CREATE TABLE "subagent_executions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parent_container_id" character varying NOT NULL, "child_container_id" character varying, "delegation_contract_id" uuid, "lineage_trace_id" character varying(255), "lineage_parent_trace_id" character varying(255), "parent_session_tree_id" character varying, "depth" integer NOT NULL DEFAULT '0', "status" "public"."subagent_executions_status_enum" NOT NULL DEFAULT 'Spawning', "result" jsonb, "assigned_files" jsonb, "subagent_chat_session_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP, CONSTRAINT "PK_1587a2a2f158573c9c8d0e9451c" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_24f4b060f71ce1142e97533f43" ON "subagent_executions" ("parent_container_id") ;`,
  `CREATE INDEX "IDX_3f67904fdbca660994dba59f62" ON "subagent_executions" ("child_container_id") ;`,
  `CREATE INDEX "IDX_fe6798fbf0da0bd1b9001c0bc2" ON "subagent_executions" ("delegation_contract_id") ;`,
  `CREATE INDEX "IDX_62f3a0e57c253f0e8a980a46c7" ON "subagent_executions" ("lineage_trace_id") ;`,
  `CREATE INDEX "IDX_2172a63ab317de7f1dafc88df0" ON "subagent_executions" ("subagent_chat_session_id") ;`,
  `CREATE TYPE "public"."delegation_contracts_target_tier_enum" AS ENUM('light', 'heavy');`,
  `CREATE TYPE "public"."delegation_contracts_status_enum" AS ENUM('queued', 'running', 'completed', 'failed', 'cancelled', 'timed_out', 'denied');`,
  `CREATE TABLE "delegation_contracts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflow_run_id" character varying NOT NULL, "parent_container_id" character varying NOT NULL, "parent_execution_id" character varying(255), "parent_delegation_id" uuid, "subagent_execution_id" character varying(255), "requester_agent_profile" character varying(255), "target_agent_profile" character varying NOT NULL, "objective" text NOT NULL, "task_prompt" text NOT NULL, "success_criteria" jsonb, "requested_tools" jsonb NOT NULL, "effective_tools" jsonb NOT NULL, "allowed_tools" jsonb, "denied_tools" jsonb, "assigned_files" jsonb, "target_tier" "public"."delegation_contracts_target_tier_enum" NOT NULL DEFAULT 'heavy', "token_budget" integer, "time_budget_ms" integer, "max_retries" integer NOT NULL DEFAULT '0', "attempt_count" integer NOT NULL DEFAULT '0', "queue_priority" integer NOT NULL DEFAULT '100', "escalation_path" jsonb, "expected_artifacts" jsonb, "metadata" jsonb, "governance_decision" jsonb, "status" "public"."delegation_contracts_status_enum" NOT NULL DEFAULT 'queued', "deadline_at" TIMESTAMP WITH TIME ZONE, "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "last_error" text, "trace_id" character varying(255) NOT NULL, "parent_trace_id" character varying(255), "lineage_depth" integer NOT NULL DEFAULT '0', "lineage_path" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_487af9ca302ba7235a1cff23255" UNIQUE ("trace_id"), CONSTRAINT "PK_a316ef1cd2f89afde2f704019de" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_6e224258585bb0c273f6ba71e1" ON "delegation_contracts" ("workflow_run_id") ;`,
  `CREATE INDEX "IDX_db6ff31109c807418aee6aa13e" ON "delegation_contracts" ("parent_container_id") ;`,
  `CREATE INDEX "IDX_cbb20ad6c7bb958316c5978c3f" ON "delegation_contracts" ("parent_execution_id") ;`,
  `CREATE INDEX "IDX_e87997ff163721f9d824d65a0f" ON "delegation_contracts" ("parent_delegation_id") ;`,
  `CREATE INDEX "IDX_e8ccb6f274209138c05564f608" ON "delegation_contracts" ("subagent_execution_id") ;`,
  `CREATE INDEX "IDX_487af9ca302ba7235a1cff2325" ON "delegation_contracts" ("trace_id") ;`,
  `CREATE INDEX "IDX_a56b9ea39b227dea24ef23643b" ON "delegation_contracts" ("parent_trace_id") ;`,
  `CREATE INDEX "idx_delegation_contracts_run_created" ON "delegation_contracts" ("workflow_run_id", "created_at") ;`,
  `CREATE INDEX "idx_delegation_contracts_parent_status_priority" ON "delegation_contracts" ("parent_container_id", "status", "queue_priority") ;`,
  `CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_type" character varying NOT NULL, "actor_id" character varying NOT NULL, "resource_id" character varying, "action" character varying NOT NULL, "result" character varying NOT NULL, "metadata" jsonb, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_d4bbd861731298b2b1488683d4" ON "audit_logs" ("event_type") ;`,
  `CREATE INDEX "IDX_177183f29f438c488b5e8510cd" ON "audit_logs" ("actor_id") ;`,
  `CREATE INDEX "IDX_62408b952557958fd12867cfeb" ON "audit_logs" ("resource_id") ;`,
  `CREATE INDEX "IDX_88dcc148d532384790ab874c3d" ON "audit_logs" ("timestamp") ;`,
  `CREATE TABLE "cost_tracking" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resource_type" character varying NOT NULL, "model" character varying, "units_consumed" double precision NOT NULL DEFAULT '0', "cost_usd" double precision NOT NULL DEFAULT '0', "workflow_run_id" character varying, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3e5a4555e969dcd9b77d8a6325c" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_25645328a317d812765b9fbfd9" ON "cost_tracking" ("resource_type") ;`,
  `CREATE INDEX "IDX_c892ee559690047203116f9e7e" ON "cost_tracking" ("timestamp") ;`,
  `CREATE TABLE "secret_store" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "encrypted_value" text NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_80a592ee31e500c5ba305a82584" UNIQUE ("name"), CONSTRAINT "PK_980386c728d11abbcef06e6a318" PRIMARY KEY ("id"));`,
  `CREATE TABLE "llm_providers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "auth_type" character varying NOT NULL DEFAULT 'api_key', "secret_id" uuid, "runtime_env" jsonb NOT NULL DEFAULT '{}', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ffeba8a7b7ae85e8c1a76f7440a" UNIQUE ("name"), CONSTRAINT "PK_98a22bf2f8befea87081c600b3f" PRIMARY KEY ("id"));`,
  `CREATE TABLE "llm_models" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "provider_name" text, "token_limit" integer NOT NULL DEFAULT '128000', "default_for_execution" boolean NOT NULL DEFAULT false, "default_for_distillation" boolean NOT NULL DEFAULT false, "default_for_summarization" boolean NOT NULL DEFAULT false, "default_for_session" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f115b447d81dacb185a3f42f4fc" UNIQUE ("name"), CONSTRAINT "PK_315c88e45d5dec7ededa8b05507" PRIMARY KEY ("id"));`,
  `CREATE TYPE "public"."mcp_servers_transport_type_enum" AS ENUM('stdio', 'http');`,
  `CREATE TYPE "public"."mcp_servers_last_status_enum" AS ENUM('unknown', 'connected', 'failed', 'disabled');`,
  `CREATE TABLE "mcp_servers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "transport_type" "public"."mcp_servers_transport_type_enum" NOT NULL, "command" text, "args" jsonb, "url" text, "headers" jsonb, "include_tools" jsonb, "exclude_tools" jsonb, "timeout_ms" integer NOT NULL DEFAULT '30000', "connect_timeout_ms" integer NOT NULL DEFAULT '10000', "max_retries" integer NOT NULL DEFAULT '2', "retry_backoff_ms" integer NOT NULL DEFAULT '1000', "last_status" "public"."mcp_servers_last_status_enum" NOT NULL DEFAULT 'unknown', "last_error" text, "last_connected_at" TIMESTAMP WITH TIME ZONE, "last_discovered_at" TIMESTAMP WITH TIME ZONE, "last_discovered_tool_count" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2ee0138f3dd9575eedd37f2405f" UNIQUE ("name"), CONSTRAINT "PK_c781b3dc7cb2a5d19460b71914d" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_mcp_servers_last_status" ON "mcp_servers" ("last_status") ;`,
  `CREATE INDEX "idx_mcp_servers_enabled" ON "mcp_servers" ("enabled") ;`,
  `CREATE TYPE "public"."acp_servers_auth_type_enum" AS ENUM('none', 'bearer', 'api_key');`,
  `CREATE TYPE "public"."acp_servers_default_run_mode_enum" AS ENUM('sync', 'async', 'stream');`,
  `CREATE TYPE "public"."acp_servers_await_policy_enum" AS ENUM('surface-to-user', 'auto-resume', 'fail');`,
  `CREATE TYPE "public"."acp_servers_last_status_enum" AS ENUM('unknown', 'connected', 'failed', 'disabled');`,
  `CREATE TABLE "acp_servers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "url" text NOT NULL, "auth_type" "public"."acp_servers_auth_type_enum" NOT NULL DEFAULT 'none', "auth_token" text, "headers" jsonb, "timeout_ms" integer NOT NULL DEFAULT '30000', "connect_timeout_ms" integer NOT NULL DEFAULT '10000', "max_retries" integer NOT NULL DEFAULT '2', "retry_backoff_ms" integer NOT NULL DEFAULT '1000', "default_run_mode" "public"."acp_servers_default_run_mode_enum" NOT NULL DEFAULT 'async', "await_policy" "public"."acp_servers_await_policy_enum" NOT NULL DEFAULT 'surface-to-user', "include_agents" jsonb, "exclude_agents" jsonb, "last_status" "public"."acp_servers_last_status_enum" NOT NULL DEFAULT 'unknown', "last_error" text, "last_connected_at" TIMESTAMP WITH TIME ZONE, "last_discovered_at" TIMESTAMP WITH TIME ZONE, "last_discovered_agent_count" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_caddeb03610a396562ad27b76a5" UNIQUE ("name"), CONSTRAINT "PK_8d3603f5b250a76478dc4d386ad" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_acp_servers_last_status" ON "acp_servers" ("last_status") ;`,
  `CREATE INDEX "idx_acp_servers_enabled" ON "acp_servers" ("enabled") ;`,
  `CREATE TABLE "acp_discovered_agents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "server_id" uuid NOT NULL, "agent_name" character varying(63) NOT NULL, "description" text, "input_content_types" jsonb, "output_content_types" jsonb, "manifest_metadata" jsonb, "registry_tool_name" character varying, "is_registered" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5c470a003bf238c3d633f96f7e2" UNIQUE ("registry_tool_name"), CONSTRAINT "PK_9a2c29cf6c83268f389335adbd7" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_acp_discovered_agents_registry_tool_name" ON "acp_discovered_agents" ("registry_tool_name") ;`,
  `CREATE INDEX "idx_acp_discovered_agents_server_id" ON "acp_discovered_agents" ("server_id") ;`,
  `CREATE TABLE "agent_skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(64) NOT NULL, "description" character varying(1024) NOT NULL, "skill_markdown" text NOT NULL, "compatibility" character varying(500), "metadata" jsonb, "source" character varying(32) NOT NULL DEFAULT 'admin', "created_by_profile" character varying(128), "created_by_workflow_run_id" character varying, "version" integer NOT NULL DEFAULT '1', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_agent_skills_name" UNIQUE ("name"), CONSTRAINT "PK_12090b937204870afb85bf39cb8" PRIMARY KEY ("id"));`,
  `CREATE TABLE "agent_profile_skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agent_profile_id" uuid NOT NULL, "skill_id" uuid NOT NULL, "assignment_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_agent_profile_skills_profile_skill" UNIQUE ("agent_profile_id", "skill_id"), CONSTRAINT "PK_4784aa81e8176874c7ad882be51" PRIMARY KEY ("id"));`,
  `CREATE TABLE "agent_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "system_prompt" text, "model_name" text, "provider_name" text, "tier_preference" text, "allowed_tools" text, "denied_tools" text, "approval_required_tools" text, "allowed_mount_aliases" text, "denied_mount_aliases" text, "allow_rw_mount_aliases" text, "assigned_skills" text, "source" character varying(32) NOT NULL DEFAULT 'admin', "created_by_profile" character varying(128), "created_by_workflow_run_id" character varying, "factory_context" jsonb, "tool_policy" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_73c9937888ee041f4e4cf915f5d" UNIQUE ("name"), CONSTRAINT "PK_4583ee140a2222f8fcecf3ac023" PRIMARY KEY ("id"));`,
  `CREATE TABLE "learning_candidates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scope_type" character varying(80) NOT NULL DEFAULT 'global', "scope_id" character varying(160), "candidate_type" character varying(64) NOT NULL, "title" character varying(220) NOT NULL, "summary" text NOT NULL, "fingerprint" character varying(64) NOT NULL, "signals_json" jsonb NOT NULL DEFAULT '{}', "score" double precision NOT NULL DEFAULT '0', "confidence" double precision NOT NULL DEFAULT '0', "recurrence_count" integer NOT NULL DEFAULT '1', "stage_diversity_count" integer NOT NULL DEFAULT '1', "failure_reduction_relevance" double precision NOT NULL DEFAULT '0', "recency_decay" double precision NOT NULL DEFAULT '1', "source_quality_confidence" double precision NOT NULL DEFAULT '0', "status" character varying(32) NOT NULL DEFAULT 'pending', "diagnostics_json" jsonb, "promoted_memory_segment_id" uuid, "promoted_at" TIMESTAMP WITH TIME ZONE, "first_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "last_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57b069cc41566a96fbf1b6a0be1" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_learning_candidates_scope_status" ON "learning_candidates" ("scope_type", "scope_id", "status") ;`,
  `CREATE INDEX "idx_learning_candidates_status_score" ON "learning_candidates" ("status", "score") ;`,
  `CREATE UNIQUE INDEX "uq_learning_candidates_fingerprint" ON "learning_candidates" ("fingerprint") ;`,
  `CREATE TABLE "runtime_feedback_signal_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "dedupe_fingerprint" character varying(512) NOT NULL, "signal_type" character varying(80) NOT NULL, "source_module" character varying(120) NOT NULL, "scope_type" character varying(80) NOT NULL, "scope_id" character varying(160), "actor_json" jsonb NOT NULL DEFAULT '{}', "affected_json" jsonb NOT NULL DEFAULT '{}', "evidence_json" jsonb NOT NULL DEFAULT '[]', "examples_json" jsonb NOT NULL DEFAULT '[]', "occurrence_count" integer NOT NULL DEFAULT '0', "max_confidence" double precision NOT NULL DEFAULT '0', "max_severity" character varying(20) NOT NULL, "first_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL, "candidate_id" uuid, "candidate_created_at" TIMESTAMP WITH TIME ZONE, "cooldown_until" TIMESTAMP WITH TIME ZONE, "last_skipped_reason" character varying(160), "diagnostics_json" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_852c899ed5763d98888dd467465" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_runtime_feedback_signal_groups_candidate" ON "runtime_feedback_signal_groups" ("candidate_id") ;`,
  `CREATE INDEX "idx_runtime_feedback_signal_groups_type_scope" ON "runtime_feedback_signal_groups" ("signal_type", "scope_type", "scope_id") ;`,
  `CREATE UNIQUE INDEX "uq_runtime_feedback_signal_groups_fingerprint" ON "runtime_feedback_signal_groups" ("dedupe_fingerprint") ;`,
  `CREATE TABLE "skill_improvement_proposals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "learning_candidate_id" uuid, "target_skill_name" character varying(120) NOT NULL, "proposal_title" character varying(220) NOT NULL, "proposal_summary" text NOT NULL, "patch_markdown" text NOT NULL, "rationale" text, "status" character varying(32) NOT NULL DEFAULT 'pending', "approved_by" character varying(128), "approved_at" TIMESTAMP WITH TIME ZONE, "rejected_by" character varying(128), "rejected_at" TIMESTAMP WITH TIME ZONE, "rejection_reason" text, "applied_at" TIMESTAMP WITH TIME ZONE, "error_message" text, "diagnostics_json" jsonb, "generated_from_run_id" character varying(96), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d5e1eb88744bc0c8aab35c7a2d9" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_skill_improvement_proposals_target_skill" ON "skill_improvement_proposals" ("target_skill_name") ;`,
  `CREATE INDEX "idx_skill_improvement_proposals_candidate_id" ON "skill_improvement_proposals" ("learning_candidate_id") ;`,
  `CREATE INDEX "idx_skill_improvement_proposals_status_created_at" ON "skill_improvement_proposals" ("status", "created_at") ;`,
  `CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "device_info" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"));`,
  `CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "resource" character varying(50) NOT NULL, "action" character varying(20) NOT NULL, CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"));`,
  `CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_id" uuid, "permission_id" uuid, CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"));`,
  `CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "description" character varying(255) NOT NULL, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"));`,
  `CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"));`,
  `CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(50) NOT NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP, "deactivated_at" TIMESTAMP, "password_changed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"));`,
  `CREATE TABLE "orchestration_session_states" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scope_id" uuid NOT NULL, "schema_version" integer NOT NULL DEFAULT '1', "last_session_id" character varying, "state_json" jsonb NOT NULL DEFAULT '{}'::jsonb, "session_lock" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f45051c3a81b382afdc0947d3b3" PRIMARY KEY ("id"));`,
  `CREATE UNIQUE INDEX "idx_orchestration_session_states_scope_id" ON "orchestration_session_states" ("scope_id") ;`,
  `CREATE TABLE "orchestration_decision_log_archive" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scope_id" uuid NOT NULL, "session_id" character varying NOT NULL, "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL, "decision" text NOT NULL, "rationale" text NOT NULL, "outcome" text, "archived_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_629c308c5c3f5c400f5396ec922" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_orchestration_decision_log_archive_occurred_at" ON "orchestration_decision_log_archive" ("occurred_at") ;`,
  `CREATE INDEX "idx_orchestration_decision_log_archive_scope_id" ON "orchestration_decision_log_archive" ("scope_id") ;`,
  `CREATE TABLE "workflow_run_todos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflow_run_id" uuid NOT NULL, "scope_id" uuid, "context_id" uuid, "title" character varying(500) NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'not-started', "order_index" integer NOT NULL DEFAULT '0', "source_context_item_id" character varying(255), "source_kind" character varying(32) NOT NULL DEFAULT 'manual', "is_archived" boolean NOT NULL DEFAULT false, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c886013ad57d7b0753d819b322c" PRIMARY KEY ("id"));`,
  `CREATE UNIQUE INDEX "uq_workflow_run_todos_run_context_item" ON "workflow_run_todos" ("workflow_run_id", "source_context_item_id") WHERE "source_context_item_id" IS NOT NULL;`,
  `CREATE INDEX "idx_workflow_run_todos_context_id" ON "workflow_run_todos" ("context_id") ;`,
  `CREATE INDEX "idx_workflow_run_todos_scope_id" ON "workflow_run_todos" ("scope_id") ;`,
  `CREATE INDEX "idx_workflow_run_todos_run_id" ON "workflow_run_todos" ("workflow_run_id") ;`,
  `CREATE TABLE "inception_chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" character varying NOT NULL, "scope_id" character varying NOT NULL, "role" character varying(10) NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_98b0aa071dc3c14bf3c425447be" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_cff50c80197a6eca2cc98a159d" ON "inception_chat_messages" ("session_id") ;`,
  `CREATE TABLE "setup_config" ("key" character varying(50) NOT NULL, "requires_setup" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_5d2778c566ad0f39bb1539a4691" PRIMARY KEY ("key"));`,
  `CREATE TABLE "system_settings" ("key" character varying(100) NOT NULL, "value" jsonb NOT NULL, "description" text, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b1b5bc664526d375c94ce9ad43d" PRIMARY KEY ("key"));`,
  `CREATE TABLE "workflow_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflow_run_id" character varying NOT NULL, "event_type" character varying NOT NULL, "step_id" character varying, "job_id" character varying, "actor_id" character varying, "correlation_id" character varying, "payload" jsonb, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f269c47134b892d9938e4c21e6f" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_d97b61b6a0d3a64d85bdc58893" ON "workflow_events" ("workflow_run_id") ;`,
  `CREATE INDEX "IDX_d6dc21c16177224511480066f4" ON "workflow_events" ("workflow_run_id", "timestamp") ;`,
  `CREATE TABLE "event_ledger" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "domain" character varying NOT NULL, "event_name" character varying NOT NULL, "outcome" character varying NOT NULL, "severity" character varying NOT NULL DEFAULT 'info', "source" character varying NOT NULL DEFAULT 'api', "actor_type" character varying, "actor_id" character varying, "scope_id" character varying, "context_id" character varying, "workflow_id" character varying, "workflow_run_id" character varying, "job_id" character varying, "step_id" character varying, "tool_id" character varying, "tool_name" character varying, "subagent_execution_id" character varying, "session_tree_id" character varying, "request_id" character varying, "correlation_id" character varying, "parent_event_id" character varying, "payload" jsonb, "error_code" character varying, "error_message" text, "occurred_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d5847202803f2f888b5e2cc2515" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_6d4a0023db230d0bced816720a" ON "event_ledger" ("correlation_id") ;`,
  `CREATE INDEX "IDX_ba4563ef005561d58f847004d4" ON "event_ledger" ("scope_id", "context_id", "occurred_at") ;`,
  `CREATE INDEX "IDX_9d1879145138e7ee67264836af" ON "event_ledger" ("workflow_run_id", "occurred_at") ;`,
  `CREATE INDEX "IDX_854d1267a4eea0a85afa8241f5" ON "event_ledger" ("domain", "event_name", "occurred_at") ;`,
  `CREATE INDEX "IDX_bb274d74a36dc84aa4d2ecce35" ON "event_ledger" ("occurred_at") ;`,
  `CREATE TABLE "tool_artifacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tool_name" character varying(255) NOT NULL, "language" character varying(16) NOT NULL DEFAULT 'node', "source_code" text NOT NULL, "test_spec" text, "schema" jsonb NOT NULL, "checksum" character varying(64) NOT NULL, "version" integer NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'draft', "latest_validation_run_id" uuid, "is_active" boolean NOT NULL DEFAULT false, "validated_at" TIMESTAMP WITH TIME ZONE, "published_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf090a6844887546ca246571d9" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_a17aaf4a7de5d9792334ebddf2" ON "tool_artifacts" ("tool_name") ;`,
  `CREATE INDEX "IDX_eea526f2d3a8bb1da83729cbff" ON "tool_artifacts" ("status") ;`,
  `CREATE INDEX "IDX_fc87b77a2614beb0e2f383b4b6" ON "tool_artifacts" ("is_active") ;`,
  `CREATE UNIQUE INDEX "IDX_60974a6851a3bb5940096a4840" ON "tool_artifacts" ("tool_name", "version") ;`,
  `CREATE TABLE "web_automation_failure_artifacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflow_run_id" uuid NOT NULL, "step_id" character varying(255) NOT NULL, "action_name" character varying(64) NOT NULL, "action_payload" jsonb NOT NULL, "selector_trace" jsonb, "attempts" jsonb NOT NULL, "attempt_count" integer NOT NULL, "duration_ms" integer NOT NULL, "error_message" text NOT NULL, "dom_snapshot_hash" character varying(64), "dom_snapshot" text, "screenshot_base64" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bc71af2989f3991e408da0a9dc6" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_0c736ed9dce804fb83675052ae" ON "web_automation_failure_artifacts" ("workflow_run_id") ;`,
  `CREATE INDEX "IDX_5a95c8733bb05bcb36c8568150" ON "web_automation_failure_artifacts" ("step_id") ;`,
  `CREATE INDEX "IDX_9c2329894ce89dd11f715fd375" ON "web_automation_failure_artifacts" ("action_name") ;`,
  `CREATE INDEX "IDX_caed6fb6d83b600ae054ce3d37" ON "web_automation_failure_artifacts" ("workflow_run_id", "created_at") ;`,
  `CREATE TABLE "tool_validation_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "artifact_id" uuid NOT NULL, "sandbox_image" character varying(255) NOT NULL, "status" character varying(32) NOT NULL, "exit_code" integer, "stdout" text, "stderr" text, "duration_ms" integer, "policy_denials" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e92618278673b044cd93e838d44" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_c0a1023dc1a561755916d0c439" ON "tool_validation_runs" ("artifact_id") ;`,
  `CREATE INDEX "IDX_6508aea30be91271c2c6d7361c" ON "tool_validation_runs" ("status") ;`,
  `CREATE TYPE "public"."automation_hooks_trigger_type_enum" AS ENUM('workflow.run.started', 'workflow.run.failed', 'resource.status.changed', 'orchestration.completed');`,
  `CREATE TYPE "public"."automation_hooks_action_type_enum" AS ENUM('invoke_workflow', 'emit_event', 'record_metadata');`,
  `CREATE TABLE "automation_hooks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scope_id" uuid NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "trigger_type" "public"."automation_hooks_trigger_type_enum" NOT NULL, "trigger_filter" jsonb, "priority" integer NOT NULL DEFAULT '100', "action_type" "public"."automation_hooks_action_type_enum" NOT NULL, "action_payload" jsonb NOT NULL DEFAULT '{}', "cooldown_window_seconds" integer NOT NULL DEFAULT '0', "last_fired_at" TIMESTAMP WITH TIME ZONE, "created_by" character varying(255), "updated_by" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e0feefd92d650ce77b9e5dfe626" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_automation_hooks_scope_enabled_priority" ON "automation_hooks" ("scope_id", "enabled", "priority") ;`,
  `CREATE INDEX "idx_automation_hooks_scope_trigger" ON "automation_hooks" ("scope_id", "trigger_type") ;`,
  `CREATE TABLE "heartbeat_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scope_id" uuid NOT NULL, "name" character varying(180) NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "interval_seconds" integer NOT NULL, "workflow_id" uuid NOT NULL, "payload_json" jsonb NOT NULL DEFAULT '{}', "next_run_at" TIMESTAMP WITH TIME ZONE, "last_run_at" TIMESTAMP WITH TIME ZONE, "created_by" character varying(255), "updated_by" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f898decff027e7827e7ea792e2" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_heartbeat_profiles_workflow" ON "heartbeat_profiles" ("workflow_id") ;`,
  `CREATE INDEX "idx_heartbeat_profiles_scope_enabled_next_run" ON "heartbeat_profiles" ("scope_id", "enabled", "next_run_at") ;`,
  `CREATE TYPE "public"."heartbeat_runs_status_enum" AS ENUM('triggered', 'running', 'succeeded', 'failed', 'skipped', 'cancelled');`,
  `CREATE TABLE "heartbeat_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "heartbeat_profile_id" uuid NOT NULL, "status" "public"."heartbeat_runs_status_enum" NOT NULL DEFAULT 'triggered', "due_at" TIMESTAMP WITH TIME ZONE NOT NULL, "triggered_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "started_at" TIMESTAMP WITH TIME ZONE, "finished_at" TIMESTAMP WITH TIME ZONE, "workflow_run_id" uuid, "error_code" character varying(120), "error_message" text, "diagnostics_json" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_be833582bfa27cab6bcba5b43d0" PRIMARY KEY ("id"));`,
  `CREATE UNIQUE INDEX "uq_heartbeat_runs_due_key" ON "heartbeat_runs" ("heartbeat_profile_id", "due_at") ;`,
  `CREATE INDEX "idx_heartbeat_runs_workflow_run" ON "heartbeat_runs" ("workflow_run_id") ;`,
  `CREATE INDEX "idx_heartbeat_runs_profile_triggered" ON "heartbeat_runs" ("heartbeat_profile_id", "triggered_at") ;`,
  `CREATE TYPE "public"."standing_orders_override_policy_enum" AS ENUM('advisory', 'allow_override', 'deny_override');`,
  `CREATE TABLE "standing_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scope_id" uuid NOT NULL, "title" character varying(180) NOT NULL, "instruction" text NOT NULL, "profile_name" character varying(120), "enabled" boolean NOT NULL DEFAULT true, "priority" integer NOT NULL DEFAULT '100', "override_policy" "public"."standing_orders_override_policy_enum" NOT NULL DEFAULT 'advisory', "created_by" character varying(255), "updated_by" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5bde7c50f20e74a2ac021a11959" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_standing_orders_scope_profile" ON "standing_orders" ("scope_id", "profile_name") ;`,
  `CREATE INDEX "idx_standing_orders_scope_enabled_priority" ON "standing_orders" ("scope_id", "enabled", "priority") ;`,
  `CREATE TYPE "public"."agent_communication_threads_urgency_enum" AS ENUM('normal', 'high');`,
  `CREATE TYPE "public"."agent_communication_threads_status_enum" AS ENUM('open', 'resolved', 'timed_out', 'denied');`,
  `CREATE TABLE "agent_communication_threads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "thread_id" character varying NOT NULL, "workflow_run_id" character varying NOT NULL, "scope_id" character varying, "context_id" character varying, "requester_execution_id" character varying, "target_agent_profile" character varying NOT NULL, "urgency" "public"."agent_communication_threads_urgency_enum" NOT NULL DEFAULT 'normal', "status" "public"."agent_communication_threads_status_enum" NOT NULL DEFAULT 'open', "message_count" integer NOT NULL DEFAULT '0', "correlation_id" character varying, "resolution_note" text, "metadata" jsonb, "last_message_at" TIMESTAMP WITH TIME ZONE, "resolved_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ade8d2e27737a2f201a6ad7471a" UNIQUE ("thread_id"), CONSTRAINT "PK_9ffccfba8f1bf5f382e568c076e" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_ade8d2e27737a2f201a6ad7471" ON "agent_communication_threads" ("thread_id") ;`,
  `CREATE INDEX "IDX_99b3d5a906a3eecb1bddcc6d7c" ON "agent_communication_threads" ("workflow_run_id") ;`,
  `CREATE INDEX "IDX_7e96d2455617b9215485ebb315" ON "agent_communication_threads" ("scope_id") ;`,
  `CREATE INDEX "IDX_f0a2b93d4692725655bfee0bde" ON "agent_communication_threads" ("context_id") ;`,
  `CREATE INDEX "IDX_4552612809270fb76ed43e9a08" ON "agent_communication_threads" ("requester_execution_id") ;`,
  `CREATE INDEX "idx_agent_communication_threads_run_requester" ON "agent_communication_threads" ("workflow_run_id", "requester_execution_id") ;`,
  `CREATE TYPE "public"."agent_communication_messages_message_kind_enum" AS ENUM('request', 'response', 'system');`,
  `CREATE TABLE "agent_communication_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "thread_id" character varying NOT NULL, "workflow_run_id" character varying NOT NULL, "sender_execution_id" character varying, "recipient_profile" character varying, "message_kind" "public"."agent_communication_messages_message_kind_enum" NOT NULL, "body" text NOT NULL, "correlation_id" character varying, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1d29d7d91d6c339ac73e49036ab" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_61def102dff8f8d88f2eff835e" ON "agent_communication_messages" ("thread_id") ;`,
  `CREATE INDEX "IDX_e9a761767d20fac65692cd2fa3" ON "agent_communication_messages" ("workflow_run_id") ;`,
  `CREATE INDEX "IDX_2eb3d678abdda75fda26ab16ae" ON "agent_communication_messages" ("correlation_id") ;`,
  `CREATE INDEX "idx_agent_communication_messages_thread_created" ON "agent_communication_messages" ("thread_id", "created_at") ;`,
  `CREATE TYPE "public"."agent_war_room_session_status_enum" AS ENUM('open', 'closed');`,
  `CREATE TYPE "public"."agent_war_room_consensus_state_enum" AS ENUM('collecting_input', 'draft_ready', 'partial_signoff', 'consensus_reached', 'deadlocked', 'ceo_tie_break_applied');`,
  `CREATE TYPE "public"."agent_war_room_resolution_type_enum" AS ENUM('consensus', 'deadlock', 'ceo_tie_break', 'manual');`,
  `CREATE TABLE "agent_war_room_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" character varying NOT NULL, "workflow_run_id" character varying NOT NULL, "scope_id" uuid, "context_id" uuid, "status" "public"."agent_war_room_session_status_enum" NOT NULL DEFAULT 'open', "consensus_state" "public"."agent_war_room_consensus_state_enum" NOT NULL DEFAULT 'collecting_input', "created_by_execution_id" character varying, "moderator_profile" character varying NOT NULL DEFAULT 'ceo-agent', "resolution_type" "public"."agent_war_room_resolution_type_enum", "resolution_note" text, "metadata" jsonb, "opened_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "closed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a479286d2598738ec516fc9e772" UNIQUE ("session_id"), CONSTRAINT "PK_3b02d9d58cc99ad1d19031c18c1" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_a479286d2598738ec516fc9e77" ON "agent_war_room_sessions" ("session_id") ;`,
  `CREATE INDEX "IDX_04e2a93bbe0c03d8d21ff43ded" ON "agent_war_room_sessions" ("workflow_run_id") ;`,
  `CREATE INDEX "IDX_3f181df274c1afa74d919f7926" ON "agent_war_room_sessions" ("scope_id") ;`,
  `CREATE INDEX "IDX_4f662cfa9bf45faed8866c82d1" ON "agent_war_room_sessions" ("context_id") ;`,
  `CREATE INDEX "idx_agent_war_room_sessions_workflow_run" ON "agent_war_room_sessions" ("workflow_run_id") ;`,
  `CREATE TYPE "public"."agent_war_room_participant_role_enum" AS ENUM('architect', 'dev', 'qa', 'pm', 'moderator');`,
  `CREATE TYPE "public"."agent_war_room_participation_status_enum" AS ENUM('invited', 'active', 'left', 'declined');`,
  `CREATE TABLE "agent_war_room_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" character varying NOT NULL, "workflow_run_id" character varying NOT NULL, "agent_profile" character varying NOT NULL, "execution_id" character varying, "role" "public"."agent_war_room_participant_role_enum" NOT NULL, "participation_status" "public"."agent_war_room_participation_status_enum" NOT NULL DEFAULT 'invited', "joined_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_471651edefc2b5354fd79d64b6a" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_2c990f5189190149cf70ea8701" ON "agent_war_room_participants" ("session_id") ;`,
  `CREATE INDEX "IDX_81904d6a2e9d50a934daa8b98b" ON "agent_war_room_participants" ("workflow_run_id") ;`,
  `CREATE INDEX "IDX_424158a47c591540a3810c39c2" ON "agent_war_room_participants" ("agent_profile") ;`,
  `CREATE UNIQUE INDEX "idx_agent_war_room_participants_session_agent_unique" ON "agent_war_room_participants" ("session_id", "agent_profile") ;`,
  `CREATE TYPE "public"."agent_war_room_message_kind_enum" AS ENUM('proposal', 'question', 'response', 'system');`,
  `CREATE TABLE "agent_war_room_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" character varying NOT NULL, "workflow_run_id" character varying NOT NULL, "sender_execution_id" character varying, "sender_profile" character varying, "message_kind" "public"."agent_war_room_message_kind_enum" NOT NULL, "body" text NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dd6e5e37130dd8eb18df79a9166" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_84ff7a012e2988a633b3b7fc95" ON "agent_war_room_messages" ("session_id") ;`,
  `CREATE INDEX "IDX_b5e7b5116ff7ecd52906d925d0" ON "agent_war_room_messages" ("workflow_run_id") ;`,
  `CREATE INDEX "idx_agent_war_room_messages_session_created" ON "agent_war_room_messages" ("session_id", "created_at") ;`,
  `CREATE TABLE "agent_war_room_blackboard" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" character varying NOT NULL, "workflow_run_id" character varying NOT NULL, "version" integer NOT NULL, "strategy_summary" text, "risks" jsonb, "decision_log" jsonb, "implementation_plan_ref" text, "updated_by_execution_id" character varying, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e9b28a636d9d420b04c03e79f4" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_84b14b5eeb9bc47e9a82058789" ON "agent_war_room_blackboard" ("session_id") ;`,
  `CREATE INDEX "IDX_d04b72a10cfdb18df8972930c0" ON "agent_war_room_blackboard" ("workflow_run_id") ;`,
  `CREATE UNIQUE INDEX "idx_agent_war_room_blackboard_session_version_unique" ON "agent_war_room_blackboard" ("session_id", "version") ;`,
  `CREATE TYPE "public"."agent_war_room_signoff_decision_enum" AS ENUM('approved', 'changes_requested', 'blocked');`,
  `CREATE TABLE "agent_war_room_signoffs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" character varying NOT NULL, "workflow_run_id" character varying NOT NULL, "role" "public"."agent_war_room_participant_role_enum" NOT NULL, "agent_profile" character varying NOT NULL, "decision" "public"."agent_war_room_signoff_decision_enum" NOT NULL, "rationale" text, "submitted_by_execution_id" character varying, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_29a09afec19057cbb49d8e32986" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_f1692bb2b9ecc1822c751432e8" ON "agent_war_room_signoffs" ("session_id") ;`,
  `CREATE INDEX "IDX_c334a9f759ebca4b514d5dbbd8" ON "agent_war_room_signoffs" ("workflow_run_id") ;`,
  `CREATE INDEX "IDX_7713d0234bce558f72c7f19d46" ON "agent_war_room_signoffs" ("agent_profile") ;`,
  `CREATE UNIQUE INDEX "idx_agent_war_room_signoffs_session_role_agent_unique" ON "agent_war_room_signoffs" ("session_id", "role", "agent_profile") ;`,
  `CREATE TABLE "doctor_repair_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action_id" character varying(120) NOT NULL, "status" character varying(32) NOT NULL, "dry_run" boolean NOT NULL DEFAULT false, "requested_by" character varying(255), "input_json" jsonb, "result_json" jsonb, "evidence_json" jsonb, "error_message" text, "started_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "finished_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0e76ab9b22185cd5a629eb48952" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_doctor_repair_history_started_at" ON "doctor_repair_history" ("started_at") ;`,
  `CREATE INDEX "idx_doctor_repair_history_status" ON "doctor_repair_history" ("status") ;`,
  `CREATE INDEX "idx_doctor_repair_history_action" ON "doctor_repair_history" ("action_id") ;`,
  `CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "scope_id" uuid, "channel" character varying(64) NOT NULL, "external_recipient_id" character varying(128) NOT NULL, "subject" character varying(255) NOT NULL, "body" text NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'pending', "event_type" character varying(128) NOT NULL, "correlation_id" character varying(255), "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "sent_at" TIMESTAMP WITH TIME ZONE, "failed_at" TIMESTAMP WITH TIME ZONE, "error_message" text, "read_at" TIMESTAMP WITH TIME ZONE, "read_by_user_id" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_notifications_event_type" ON "notifications" ("event_type") ;`,
  `CREATE INDEX "idx_notifications_user_id_created" ON "notifications" ("user_id", "created_at") ;`,
  `CREATE INDEX "idx_notifications_status_channel_created" ON "notifications" ("status", "channel", "created_at") ;`,
  `CREATE TABLE "tool_approval_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scope_type" character varying NOT NULL, "scope_id" character varying, "tool_name" character varying NOT NULL, "effect" character varying NOT NULL, "priority" integer NOT NULL DEFAULT '0', "argument_patterns" jsonb, "created_by" character varying, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17af69c9b65cee40c8722eabed5" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_1e87d3b16b82406617796ed189" ON "tool_approval_rules" ("tool_name") ;`,
  `CREATE INDEX "IDX_84ecab4481cd32ad58e4d75e9c" ON "tool_approval_rules" ("scope_type", "scope_id") ;`,
  `CREATE TABLE "tool_call_approval_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflow_run_id" character varying NOT NULL, "job_id" character varying NOT NULL, "scope_id" character varying, "chat_session_id" character varying, "tool_name" character varying NOT NULL, "tool_arguments" jsonb NOT NULL, "requested_by" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "approved_by" character varying, "approved_at" TIMESTAMP WITH TIME ZONE, "rejected_by" character varying, "rejected_at" TIMESTAMP WITH TIME ZONE, "rejection_reason" text, "resolution_rule_id" uuid, "correlation_id" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_29998b8cce5eff1bfa19c9d62a9" UNIQUE ("correlation_id"), CONSTRAINT "PK_a8d76d442faa8a95a771da291dc" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_de151887fd9e04f87aaa8b2ea8" ON "tool_call_approval_requests" ("chat_session_id", "status") ;`,
  `CREATE INDEX "IDX_cdc0feebfe7aa851d8607aeb9d" ON "tool_call_approval_requests" ("workflow_run_id", "status") ;`,
  `CREATE INDEX "IDX_7e81759db407e3f15386707c0e" ON "tool_call_approval_requests" ("scope_id", "status") ;`,
  `CREATE INDEX "IDX_77847ff47d5ce90a1d0a3235f1" ON "tool_call_approval_requests" ("status") ;`,
  `CREATE TABLE "user_channel_identities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "channel" character varying(64) NOT NULL, "external_user_id" character varying(128) NOT NULL, "label" character varying(64), "is_verified" boolean NOT NULL DEFAULT false, "is_notifications_destination" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_user_channel_identities_user_channel_external" UNIQUE ("user_id", "channel", "external_user_id"), CONSTRAINT "PK_d343ea7da3ee8ab7ce6f73dfb20" PRIMARY KEY ("id"));`,
  `CREATE TABLE "chat_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" character varying(20) NOT NULL DEFAULT 'STARTING', "execution_state" character varying(32) NOT NULL DEFAULT 'starting', "retry_metadata" jsonb, "failure_info" jsonb, "session_type" character varying(20) NOT NULL DEFAULT 'general', "agent_profile_id" uuid NOT NULL, "agent_profile_name" character varying(255) NOT NULL, "scope_id" uuid, "initial_message" text NOT NULL, "display_name" character varying(512), "container_id" character varying(128), "container_tier" smallint NOT NULL DEFAULT '2', "provider" character varying(64), "model" character varying(128), "system_prompt" text, "session_tree_id" uuid, "workflow_run_id" uuid, "parent_chat_session_id" uuid, "subagent_execution_id" character varying(255), "error_message" text, "source" character varying(64) NOT NULL DEFAULT 'ad-hoc', "context_metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_efc151a4aafa9a28b73dedc485f" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_4680547e20c7483edc930ab1c4" ON "chat_sessions" ("status") ;`,
  `CREATE INDEX "IDX_a30503bcbc32d20ac63c647bd0" ON "chat_sessions" ("execution_state") ;`,
  `CREATE INDEX "IDX_afdbb1c6c0c87a17650d9a0fde" ON "chat_sessions" ("session_type") ;`,
  `CREATE INDEX "IDX_879e18b6951cb1b4f0fea6dfa0" ON "chat_sessions" ("agent_profile_id") ;`,
  `CREATE INDEX "IDX_b285f24cf8120486de4c28fa18" ON "chat_sessions" ("scope_id") ;`,
  `CREATE INDEX "IDX_a0e6dd84867794afb22b5a2800" ON "chat_sessions" ("parent_chat_session_id") ;`,
  `CREATE INDEX "IDX_50fa8f1e4c9aa694e667c87656" ON "chat_sessions" ("subagent_execution_id") ;`,
  `CREATE INDEX "IDX_8b3d72f6e2ea4d5a88de0a04eb" ON "chat_sessions" ("source") ;`,
  `CREATE TABLE "chat_channel_routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider" character varying(64) NOT NULL, "external_thread_id" character varying(128) NOT NULL, "external_user_id" character varying(128) NOT NULL, "active_chat_session_id" uuid NOT NULL, "last_accessed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fbaae734860d90653dca2e1b909" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_chat_channel_routes_active_session" ON "chat_channel_routes" ("active_chat_session_id") ;`,
  `CREATE UNIQUE INDEX "idx_chat_channel_routes_identity_unique" ON "chat_channel_routes" ("provider", "external_thread_id", "external_user_id") ;`,
  `CREATE TABLE "chat_memory_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_id" character varying(128) NOT NULL, "event_type" character varying(64) NOT NULL, "correlation_id" character varying(128) NOT NULL, "chat_session_id" character varying(128) NOT NULL, "memory_id" uuid NOT NULL, "action" character varying(16) NOT NULL, "profile_id" uuid, "envelope" jsonb NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_15081581f802cc8f36c92ee1380" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_chat_memory_events_session_created" ON "chat_memory_events" ("chat_session_id", "created_at") ;`,
  `CREATE INDEX "idx_chat_memory_events_type_created" ON "chat_memory_events" ("event_type", "created_at") ;`,
  `CREATE TABLE "chat_memory_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_type" character varying(32) NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "chat_session_id" uuid, "profile_id" uuid, "idempotency_key" character varying(255) NOT NULL, "trigger_reason" character varying(64) NOT NULL, "payload" jsonb, "attempts" integer NOT NULL DEFAULT '0', "max_attempts" integer NOT NULL DEFAULT '3', "scheduled_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "last_error" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d99f5114d09f8aa1ec3761c2369" PRIMARY KEY ("id"));`,
  `CREATE UNIQUE INDEX "idx_chat_memory_jobs_idempotency" ON "chat_memory_jobs" ("idempotency_key") ;`,
  `CREATE INDEX "idx_chat_memory_jobs_status_scheduled" ON "chat_memory_jobs" ("status", "scheduled_at") ;`,
  `CREATE TABLE "chat_memory_promotion_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chat_session_id" uuid, "profile_id" uuid NOT NULL, "session_memory_id" uuid, "profile_memory_id" uuid NOT NULL, "action" character varying(16) NOT NULL, "idempotency_key" character varying(255) NOT NULL, "trigger_reason" character varying(64) NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d2c03ecb0c1cafedf18f2779205" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_chat_memory_promotion_audit_profile_created" ON "chat_memory_promotion_audit" ("profile_id", "created_at") ;`,
  `CREATE UNIQUE INDEX "idx_chat_memory_promotion_audit_idempotency" ON "chat_memory_promotion_audit" ("idempotency_key") ;`,
  `CREATE TABLE "chat_profile_memory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "profile_id" uuid NOT NULL, "last_chat_session_id" uuid, "memory_type" character varying(32) NOT NULL DEFAULT 'fact', "content" text NOT NULL, "normalized_content" text NOT NULL, "confidence_score" smallint NOT NULL DEFAULT '50', "promotion_count" integer NOT NULL DEFAULT '1', "last_promoted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_accessed_at" TIMESTAMP WITH TIME ZONE, "archived_at" TIMESTAMP WITH TIME ZONE, "provenance" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_59351075a20dfd181328d250611" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_chat_profile_memory_profile_normalized" ON "chat_profile_memory" ("profile_id", "normalized_content") ;`,
  `CREATE INDEX "idx_chat_profile_memory_profile_updated" ON "chat_profile_memory" ("profile_id", "updated_at") ;`,
  `CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chat_session_id" uuid NOT NULL, "direction" character varying(32) NOT NULL, "sender" character varying(32) NOT NULL, "channel" character varying(64) NOT NULL, "provider_message_id" character varying(128), "correlation_id" character varying(128), "event_type" character varying(64) NOT NULL, "text" text NOT NULL, "run_id" uuid, "run_status" character varying(32), "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_7737b2da509d8769d559f354c7" ON "chat_messages" ("chat_session_id") ;`,
  `CREATE INDEX "idx_chat_messages_session_created" ON "chat_messages" ("chat_session_id", "created_at") ;`,
  `CREATE TYPE "public"."chat_session_participant_role_enum" AS ENUM('owner', 'participant', 'moderator');`,
  `CREATE TYPE "public"."chat_session_participation_status_enum" AS ENUM('invited', 'active', 'declined', 'left', 'removed');`,
  `CREATE TABLE "chat_session_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chat_session_id" character varying NOT NULL, "agent_profile" character varying NOT NULL, "role" "public"."chat_session_participant_role_enum" NOT NULL, "participation_status" "public"."chat_session_participation_status_enum" NOT NULL DEFAULT 'invited', "invited_by" character varying, "joined_at" TIMESTAMP WITH TIME ZONE, "left_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_464ccb9aeaee6a3a5a6331a8180" PRIMARY KEY ("id"));`,
  `CREATE INDEX "IDX_415f3d77a6ea05bb997f2f2c38" ON "chat_session_participants" ("chat_session_id") ;`,
  `CREATE INDEX "IDX_72f618df8791410f8610041ec4" ON "chat_session_participants" ("agent_profile") ;`,
  `CREATE INDEX "IDX_6db0024bec29e762746de562df" ON "chat_session_participants" ("invited_by") ;`,
  `CREATE UNIQUE INDEX "idx_chat_session_participants_session_agent_unique" ON "chat_session_participants" ("chat_session_id", "agent_profile") ;`,
  `CREATE TABLE "chat_session_memory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chat_session_id" uuid NOT NULL, "profile_id" uuid NOT NULL, "source_message_id" uuid, "source_role" character varying(32) NOT NULL, "memory_type" character varying(32) NOT NULL DEFAULT 'history', "content" text NOT NULL, "normalized_content" text NOT NULL, "importance_score" smallint NOT NULL DEFAULT '50', "provenance" jsonb, "promoted_profile_memory_id" uuid, "distilled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0b0a92d6b06d3ae5f4996f34b4d" PRIMARY KEY ("id"));`,
  `CREATE INDEX "idx_chat_session_memory_profile_created" ON "chat_session_memory" ("profile_id", "created_at") ;`,
  `CREATE INDEX "idx_chat_session_memory_session_created" ON "chat_session_memory" ("chat_session_id", "created_at") ;`,
  `ALTER TABLE "acp_discovered_agents" ADD CONSTRAINT "FK_fc439b76da4d2d09402c32f2a95" FOREIGN KEY ("server_id") REFERENCES "acp_servers"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE "agent_profile_skills" ADD CONSTRAINT "FK_2f78af7216c2a5c86567c1280e8" FOREIGN KEY ("agent_profile_id") REFERENCES "agent_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE "agent_profile_skills" ADD CONSTRAINT "FK_ae5187e2d95a7bfdb64857f8e4c" FOREIGN KEY ("skill_id") REFERENCES "agent_skills"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE "skill_improvement_proposals" ADD CONSTRAINT "FK_af2c349cb733e6246c5674b7a77" FOREIGN KEY ("learning_candidate_id") REFERENCES "learning_candidates"("id") ON DELETE SET NULL ON UPDATE NO ACTION;`,
  `ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE "workflow_run_todos" ADD CONSTRAINT "FK_4449bed7f5cfcc1b2fca2e4bc74" FOREIGN KEY ("workflow_run_id") REFERENCES "workflow_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE "user_channel_identities" ADD CONSTRAINT "FK_278b31ab797bb2c236ca8ec011b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;`,
];

const ROLLBACK_STATEMENTS = [
  `DROP TABLE IF EXISTS "chat_session_memory" CASCADE`,
  `DROP TABLE IF EXISTS "chat_session_participants" CASCADE`,
  `DROP TABLE IF EXISTS "chat_messages" CASCADE`,
  `DROP TABLE IF EXISTS "chat_profile_memory" CASCADE`,
  `DROP TABLE IF EXISTS "chat_memory_promotion_audit" CASCADE`,
  `DROP TABLE IF EXISTS "chat_memory_jobs" CASCADE`,
  `DROP TABLE IF EXISTS "chat_memory_events" CASCADE`,
  `DROP TABLE IF EXISTS "chat_channel_routes" CASCADE`,
  `DROP TABLE IF EXISTS "chat_sessions" CASCADE`,
  `DROP TABLE IF EXISTS "user_channel_identities" CASCADE`,
  `DROP TABLE IF EXISTS "tool_call_approval_requests" CASCADE`,
  `DROP TABLE IF EXISTS "tool_approval_rules" CASCADE`,
  `DROP TABLE IF EXISTS "notifications" CASCADE`,
  `DROP TABLE IF EXISTS "doctor_repair_history" CASCADE`,
  `DROP TABLE IF EXISTS "agent_war_room_signoffs" CASCADE`,
  `DROP TABLE IF EXISTS "agent_war_room_blackboard" CASCADE`,
  `DROP TABLE IF EXISTS "agent_war_room_messages" CASCADE`,
  `DROP TABLE IF EXISTS "agent_war_room_participants" CASCADE`,
  `DROP TABLE IF EXISTS "agent_war_room_sessions" CASCADE`,
  `DROP TABLE IF EXISTS "agent_communication_messages" CASCADE`,
  `DROP TABLE IF EXISTS "agent_communication_threads" CASCADE`,
  `DROP TABLE IF EXISTS "standing_orders" CASCADE`,
  `DROP TABLE IF EXISTS "heartbeat_runs" CASCADE`,
  `DROP TABLE IF EXISTS "heartbeat_profiles" CASCADE`,
  `DROP TABLE IF EXISTS "automation_hooks" CASCADE`,
  `DROP TABLE IF EXISTS "tool_validation_runs" CASCADE`,
  `DROP TABLE IF EXISTS "web_automation_failure_artifacts" CASCADE`,
  `DROP TABLE IF EXISTS "tool_artifacts" CASCADE`,
  `DROP TABLE IF EXISTS "event_ledger" CASCADE`,
  `DROP TABLE IF EXISTS "workflow_events" CASCADE`,
  `DROP TABLE IF EXISTS "system_settings" CASCADE`,
  `DROP TABLE IF EXISTS "setup_config" CASCADE`,
  `DROP TABLE IF EXISTS "inception_chat_messages" CASCADE`,
  `DROP TABLE IF EXISTS "workflow_run_todos" CASCADE`,
  `DROP TABLE IF EXISTS "orchestration_decision_log_archive" CASCADE`,
  `DROP TABLE IF EXISTS "orchestration_session_states" CASCADE`,
  `DROP TABLE IF EXISTS "users" CASCADE`,
  `DROP TABLE IF EXISTS "user_roles" CASCADE`,
  `DROP TABLE IF EXISTS "roles" CASCADE`,
  `DROP TABLE IF EXISTS "role_permissions" CASCADE`,
  `DROP TABLE IF EXISTS "permissions" CASCADE`,
  `DROP TABLE IF EXISTS "refresh_tokens" CASCADE`,
  `DROP TABLE IF EXISTS "skill_improvement_proposals" CASCADE`,
  `DROP TABLE IF EXISTS "runtime_feedback_signal_groups" CASCADE`,
  `DROP TABLE IF EXISTS "learning_candidates" CASCADE`,
  `DROP TABLE IF EXISTS "agent_profiles" CASCADE`,
  `DROP TABLE IF EXISTS "agent_profile_skills" CASCADE`,
  `DROP TABLE IF EXISTS "agent_skills" CASCADE`,
  `DROP TABLE IF EXISTS "acp_discovered_agents" CASCADE`,
  `DROP TABLE IF EXISTS "acp_servers" CASCADE`,
  `DROP TABLE IF EXISTS "mcp_servers" CASCADE`,
  `DROP TABLE IF EXISTS "llm_models" CASCADE`,
  `DROP TABLE IF EXISTS "llm_providers" CASCADE`,
  `DROP TABLE IF EXISTS "secret_store" CASCADE`,
  `DROP TABLE IF EXISTS "cost_tracking" CASCADE`,
  `DROP TABLE IF EXISTS "audit_logs" CASCADE`,
  `DROP TABLE IF EXISTS "delegation_contracts" CASCADE`,
  `DROP TABLE IF EXISTS "subagent_executions" CASCADE`,
  `DROP TABLE IF EXISTS "memory_segments" CASCADE`,
  `DROP TABLE IF EXISTS "pi_session_trees" CASCADE`,
  `DROP TABLE IF EXISTS "tool_registry" CASCADE`,
  `DROP TABLE IF EXISTS "workflow_launch_presets" CASCADE`,
  `DROP TABLE IF EXISTS "scheduled_job_runs" CASCADE`,
  `DROP TABLE IF EXISTS "scheduled_jobs" CASCADE`,
  `DROP TABLE IF EXISTS "workflow_runs" CASCADE`,
  `DROP TABLE IF EXISTS "workflows" CASCADE`,
  `DROP TYPE IF EXISTS "public"."chat_session_participation_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."chat_session_participant_role_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."agent_war_room_signoff_decision_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."agent_war_room_message_kind_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."agent_war_room_participation_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."agent_war_room_participant_role_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."agent_war_room_resolution_type_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."agent_war_room_consensus_state_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."agent_war_room_session_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."agent_communication_messages_message_kind_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."agent_communication_threads_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."agent_communication_threads_urgency_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."standing_orders_override_policy_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."heartbeat_runs_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."automation_hooks_action_type_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."automation_hooks_trigger_type_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."acp_servers_last_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."acp_servers_await_policy_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."acp_servers_default_run_mode_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."acp_servers_auth_type_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."mcp_servers_last_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."mcp_servers_transport_type_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."delegation_contracts_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."delegation_contracts_target_tier_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."subagent_executions_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."memory_segments_memory_type_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."scheduled_job_runs_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."scheduled_jobs_execution_target_type_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."scheduled_jobs_schedule_type_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."scheduled_jobs_status_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."scheduled_jobs_schedule_scope_enum" CASCADE`,
  `DROP TYPE IF EXISTS "public"."workflow_runs_status_enum" CASCADE`,
];

export class ApiPostCutoverBaseline20260517000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const statement of BASELINE_STATEMENTS) {
      await queryRunner.query(statement);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const statement of ROLLBACK_STATEMENTS) {
      await queryRunner.query(statement);
    }
  }
}
