import { QuestionAnswer, UserQuestion } from "@/lib/api/settings.types";
import { WorkflowRunAutonomyDiagnostics, WorkflowRunRetrospectiveTrace } from "@/lib/api/workflow-lifecycle.types";
import { ExecutionSummary, WorkflowRun, WorkflowRunGraph, WorkflowTelemetryEvent } from "@/lib/api/workflows.types";
import type { BudgetDecision } from "@/components/budget/BudgetStatusBanner";
import type { SessionChatMessage } from "@/pages/active-session/active-session.utils.types";
import type { WorkflowRunPhase } from "./WorkflowRunPhasesBanner";

export type WorkflowRunDetailContentProps = Readonly<{
  run: WorkflowRun;
  workflowId?: string;
  connectionState: string;
  telemetryError: unknown;
  phaseMarkers: WorkflowRunPhase[];
  events: WorkflowTelemetryEvent[];
  isLoadingTelemetry: boolean;
  chatMessages: SessionChatMessage[];
  chatEmptyMessage: string;
  message: string;
  onMessageChange: (value: string) => void;
  onInjectMessage: (attachmentIds?: string[]) => void;
  isInjectingMessage: boolean;
  pendingQuestions: UserQuestion[] | null;
  onSubmitAnswers: (answers: QuestionAnswer[]) => void;
  isSubmittingAnswers: boolean;
  isInteractive: boolean;
  stepOutputs: { stepId: string; output: Record<string, unknown> }[];
  runExecutions: ExecutionSummary[];
  graph?: WorkflowRunGraph | null;
  autonomyDiagnostics?: WorkflowRunAutonomyDiagnostics;
  retrospectiveTrace?: WorkflowRunRetrospectiveTrace;
  isLoadingGraph?: boolean;
  graphError?: unknown;
  initialTab?: string;
  activeSessionPath?: string;
  onBack: () => void;
  onRestartOrchestration?: () => void;
  isRestartOrchestrationPending?: boolean;
  onRestartWorkItemWorkflow?: () => void;
  isRestartWorkItemWorkflowPending?: boolean;
  onRerunOriginalWorkflow?: () => void;
  isRerunOriginalWorkflowPending?: boolean;
  workItemRestartNotice?: string | null;
  failureReason?: string;
  onAbortRun?: () => void;
  isAbortRunPending?: boolean;
  budgetDecision?: BudgetDecision | null;
  budgetReasonCode?: string | null;
  budgetEstimatedCostCents?: number | null;
  budgetRemainingCents?: number | null;
}>;
