import { WorkflowTelemetryEvent } from "@/lib/api/workflows.types";
import type { EventHandler } from "./active-session.chat-builder.types";
import { handleToolEvent } from "./active-session.chat-builder.handlers.tool";
import {
  handleAgentErrorEvent,
  handleAgentPromptSentEvent,
  handleLifecycleEvent,
  handleTurnEndEvent,
  handleUserMessage,
  handleUserMessageDeliveryFailedEvent,
  handleUserQuestionAnswersEvent,
  handleUserQuestionsPosedEvent,
  handleWorkflowControlEvent,
} from "./active-session.chat-builder.handlers.lifecycle";
import { handleSubagentLifecycleEvent } from "./active-session.chat-builder.handlers.subagent";
import {
  handleSteeringPlanApprovedEvent,
  handleSteeringPlanProposedEvent,
  handleSteeringPlanRejectedEvent,
} from "./active-session.chat-builder.handlers.steering";

export const EVENT_HANDLERS: Partial<
  Record<WorkflowTelemetryEvent["event_type"], EventHandler>
> = {
  user_message: handleUserMessage,
  "spawn.requested": handleSubagentLifecycleEvent,
  "spawn.succeeded": handleSubagentLifecycleEvent,
  "spawn.failed": handleSubagentLifecycleEvent,
  "execution.completed": handleSubagentLifecycleEvent,
  "execution.failed": handleSubagentLifecycleEvent,
  tool_execution_start: handleToolEvent,
  tool_execution_end: handleToolEvent,
  tool_execution_update: handleToolEvent,
  workflow_control: handleWorkflowControlEvent,
  "workflow.run.started": handleLifecycleEvent,
  job_start: handleLifecycleEvent,
  "invoke_workflow.child_started": handleLifecycleEvent,
  step_start: handleLifecycleEvent,
  container_starting: handleLifecycleEvent,
  container_started: handleLifecycleEvent,
  container_stopped: handleLifecycleEvent,
  container_removing: handleLifecycleEvent,
  container_removed: handleLifecycleEvent,
  session_completed: handleLifecycleEvent,
  session_failed: handleLifecycleEvent,
  session_cancelled: handleLifecycleEvent,
  agent_runtime_ready: handleLifecycleEvent,
  agent_prompt_sent: handleAgentPromptSentEvent,
  agent_mention_requested: handleLifecycleEvent,
  agent_mention_received: handleLifecycleEvent,
  agent_mention_responded: handleLifecycleEvent,
  agent_mention_timeout: handleLifecycleEvent,
  agent_thread_resolved: handleLifecycleEvent,
  agent_mention_denied: handleLifecycleEvent,
  chat_participant_invited: handleLifecycleEvent,
  chat_participant_joined: handleLifecycleEvent,
  chat_participant_invite_denied: handleLifecycleEvent,
  chat_participant_left: handleLifecycleEvent,
  chat_participant_removed: handleLifecycleEvent,
  war_room_opened: handleLifecycleEvent,
  war_room_participant_invited: handleLifecycleEvent,
  war_room_message_posted: handleLifecycleEvent,
  war_room_blackboard_updated: handleLifecycleEvent,
  war_room_signoff_submitted: handleLifecycleEvent,
  war_room_tie_break_applied: handleLifecycleEvent,
  war_room_deadlocked: handleLifecycleEvent,
  war_room_consensus_reached: handleLifecycleEvent,
  war_room_closed: handleLifecycleEvent,
  turn_end: handleTurnEndEvent,
  agent_error: handleAgentErrorEvent,
  user_message_delivery_failed: handleUserMessageDeliveryFailedEvent,
  user_questions_posed: handleUserQuestionsPosedEvent,
  user_question_answers: handleUserQuestionAnswersEvent,
  steering_plan_proposed: handleSteeringPlanProposedEvent,
  steering_plan_approved: handleSteeringPlanApprovedEvent,
  steering_plan_rejected: handleSteeringPlanRejectedEvent,
};
