import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

/**
 * Skill-improvement proposals generated by learning sweeps are reviewed and
 * actioned from the global Improvements queue, not from this project's
 * workspace. This card is a pointer only — it renders no proposal data and
 * calls no proposal-management endpoints.
 */
export function LearningTabProposalsPointerCard() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Skill Improvement Proposals</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <p className="text-sm text-muted-foreground">
          Proposals generated by learning sweeps are reviewed in the global
          Improvements queue, alongside proposals from every project.
        </p>
        <Button asChild>
          <Link to="/improvements">Go to Improvements</Link>
        </Button>
      </CardContent>
    </Card>
  );
}
