export const CHAT_SESSION_DOMAIN_PORT = Symbol('CHAT_SESSION_DOMAIN_PORT');
export const CHAT_SESSION_REPOSITORY_PORT = Symbol(
  'CHAT_SESSION_REPOSITORY_PORT',
);
export const CHAT_SESSION_MEMORY_PORT = Symbol('CHAT_SESSION_MEMORY_PORT');
export const AGENT_COMMUNICATION_DOMAIN_PORT = Symbol(
  'AGENT_COMMUNICATION_DOMAIN_PORT',
);
export const SUBAGENT_CHAT_SESSION_PORT = Symbol('SUBAGENT_CHAT_SESSION_PORT');
